### PR TITLE
Added Auto-building

### PR DESCRIPTION
**Pull request by xxAROX**

### CODE REVIEW

**Comment by J1b1x** [comment]
Bruh, this is a library, we don't need auto-building here.

**Comment by xxAROX** [comment]
OKay

**Comment by xxAROX** [comment]
I got J1b1x/Forms in mind (also a Library, also got a .phar lol)

**Comment by xxAROX** [comment]
nvm

**Comment by J1b1x** [comment]
yeah beacause the forms library can be used as both.

**Comment by J1b1x** [comment]
> I got J1b1x/Forms in mind (also a Library, also got a .phar lol)

yeah because the forms library can be used as both.

**Comment by xxAROX** [comment]
👍, have a nice weekend bro

**Pull request closed without merging**
